### ISSUE TITLE
work-around for Python 3.10

### ISSUE THREAD

**Issue by drubanov** [bpython/bpython#945]
bpython doesn't start in Python 3.10 virtualenv.
When installing it with the latest greenlet package, it fails to start with a "Memory Error".  Here's the pip freeze output:
backports.entry-points-selectable==1.1.1
blessings==1.7
bpython==0.22.1
certifi==2019.6.16
chardet==3.0.4
charset-normalizer==2.0.9
curtsies==0.3.10
cwcwidth==0.1.5
distlib==0.3.4
filelock==3.4.0
greenlet==1.1.2     <--------------
idna==2.8
platformdirs==2.4.0
Pygments==2.4.2
pyxdg==0.27
requests==2.22.0
six==1.16.0
typing==3.7.4
typing_extensions==4.0.1
urllib3==1.25.3
virtualenv==20.10.0
wcwidth==0.2.5

However, the following pip freeze works with the bpython (.18) and Python 3.9:
blessings==1.7
bpython==0.18
certifi==2019.6.16
chardet==3.0.4
curtsies==0.3.0
distlib==0.3.3
filelock==3.4.0
greenlet==0.4.16  <----------
idna==2.8
platformdirs==2.4.0
Pygments==2.4.2
requests==2.22.0
six==1.16.0
typing==3.7.4
urllib3==1.25.3
virtualenv==20.10.0
wcwidth==0.1.7

This won't work with Python 3.10 though because greenlet.c fails to compile with this error:
greenlet.c:554:10: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘use_tracing’; did you mean ‘tracing’?
under Python 3.10.  

As a work-around, I changed all imports of cwcwidth module in all of bpython's .py files, which imported cwcwidth, with an import of wcwidth module.  It works now.  And by "works" I mean that I can use bpython 0.22.1 with Python 3.10.1 (which is the latest stable release).

**Comment by thomasballinger** [comment]
Thanks for filing, I hadn't seen this yet. What OS is this on? It sounds like something to change about the requirements of cwcwidth?

I want to understand this better, but it sounds like moving off of greenlets is important.

**Comment by drubanov** [comment]
So I am comparing python 3.9 and 3.10 and bpython .18 and .22.  I am doing it on Linux Mint 19.3.
I built python versions on my own.  I am pulling in bpython's with pip.  
Greenlet is still used when I manually switched bpython .22's imports from cwcwidth to wcwidth.  I know this because renaming
site-packages/greenlet to site-packages/greenlet.unused causes 

File "/home/drubanov/pyenv/bpython310.1/lib/python3.10/site-packages/bpython/curtsiesfrontend/coderunner.py", line 14, in <module>
    import greenlet
ModuleNotFoundError: No module named 'greenlet'

when starting up bpython.  And renaming greenlet.unused back to greenlet makes bpython start up normally.

I think bpython used to use wcwidth (at least it did in .18 version).  And simply changing bpython .22 back to using wcwidth instead of cwcwidth would solve this issue.  The c... package is supposed to provide a faster implementation of the wcwidth, but it causes the following exception in python 3.10 (and 3.10.1):

Traceback (most recent call last):
  File "/home/drubanov/pyenv/bpython310.1.experiment/bin/bpython", line 5, in <module>
    from bpython.curtsies import main
  File "/home/drubanov/pyenv/bpython310.1.experiment/lib/python3.10/site-packages/bpython/curtsies.py", line 11, in <module>
    import curtsies
  File "/home/drubanov/pyenv/bpython310.1.experiment/lib/python3.10/site-packages/curtsies/__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "/home/drubanov/pyenv/bpython310.1.experiment/lib/python3.10/site-packages/curtsies/window.py", line 26, in <module>
    from .formatstring import fmtstr, FmtStr
  File "/home/drubanov/pyenv/bpython310.1.experiment/lib/python3.10/site-packages/curtsies/formatstring.py", line 25, in <module>
    from cwcwidth import wcswidth, wcwidth
  File "/home/drubanov/pyenv/bpython310.1.experiment/lib/python3.10/site-packages/cwcwidth/__init__.py", line 32, in <module>
    from ._impl import wcwidth, wcswidth
MemoryError

For reference, here's the pip freeze of packages that cause this memory error: 

$ pip freeze
backports.entry-points-selectable==1.1.1
blessings==1.7
bpython==0.22.1
certifi==2019.6.16
chardet==3.0.4
curtsies==0.3.10
cwcwidth==0.1.5
distlib==0.3.4
filelock==3.4.0
greenlet==1.1.2
idna==2.8
platformdirs==2.4.0
Pygments==2.4.2
pyxdg==0.27
requests==2.22.0
six==1.16.0
typing==3.7.4
typing_extensions==4.0.1
urllib3==1.25.3
virtualenv==20.10.0
wcwidth==0.1.7

**Comment by drubanov** [comment]
doing this in the above experimental python 3.10.1 virtualenv 

$ pip install --upgrade curtsies blessings cwcwidth wcwidth --upgrade-strategy eager

changes the packages to 

$ pip freeze
backports.entry-points-selectable==1.1.1
blessings==1.7
bpython==0.22.1
certifi==2019.6.16
chardet==3.0.4
curtsies==0.3.10
cwcwidth==0.1.5
distlib==0.3.4
filelock==3.4.0
greenlet==1.1.2
idna==2.8
platformdirs==2.4.0
Pygments==2.4.2
pyxdg==0.27
requests==2.22.0
six==1.16.0
typing==3.7.4
typing_extensions==4.0.1
urllib3==1.25.3
virtualenv==20.10.0
wcwidth==0.2.5


but it does not fix the memory error.

**Comment by sebastinas** [comment]
I am a bit confused by this report and cannot reproduce the issue. Could you please provide us with a verbose log of the install process of `cwcwidth`? And as @thomasballinger already said, please tell us more about your OS.

If `cwcwidth` was broken under Python 3.10, we would see test failures. But the tests for Python 3.10 pass.

**Comment by drubanov** [comment]
@sebastinas can you, please, let me know what more system information may be useful?  I already mentioned it was Mint 19.3.  What might be helpful? gcc version?  kernel version?  python3.10's compilation's configure options? 

At a minimum, maybe this helps?
$ uname -a
Linux Cinnamon 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I just recreated the virtual environment, installing cwcwidth before installing bpython (using pip).

The log file produced with this command is attached.

$ pip install -v -v -v --log $HOME/pyenv/cwcwidth.log cwcwidth

[cwcwidth.log](https://github.com/bpython/bpython/files/7776339/cwcwidth.log)

Hmm.  But this works now!

As of this morning, installing bpython, with pip, results in 14 requirements.  Yesterday, when it was broken, pip was pulling in 22 requirements.  wcwidth is not even being installed now!  

I am not sure where the change happened, but I certainly didn't do anything new or different (other than running pip with -v -v -v  --log options).

I guess this can be closed now.  I am sorry I can't be more helpful in figuring out why it was broken before.

**Comment by drubanov** [comment]
I should correct my statement that "I didn't do anything different."  I didn't pip-install virtualenv before installing bpython.  But installing virtualenv and bpython still only results in 19 packages being installed rather than 22.  And it still doesn't cause wcwidth to be installed.  So something changed since last night.  Anyhow, bpython 22.1 with python 10.1 works "out of the box" for me now.  So that's cool.

**Comment by sebastinas** [comment]
The difference is that I published a dedicated build of `cwcwidth` for Python 3.10 on pypi. I suspect (but without a log it's hard to confirm), that pip pulled an incorrect version of `cwcwidth` (that is: not built for Python 3.10).

**Comment by drubanov** [comment]
@sebastinas Thank you for that.  That does seem to make the difference.  Using the following requirements files ("bpython310.1.txt"):

backports.entry-points-selectable==1.1.1
blessings==1.7
bpython==0.22.1
certifi==2019.6.16
chardet==3.0.4
charset-normalizer==2.0.9
curtsies==0.3.10
cwcwidth==0.1.5
distlib==0.3.4
filelock==3.4.0
greenlet==1.1.2
idna==2.8
platformdirs==2.4.0
Pygments==2.4.2
pyxdg==0.27
requests==2.22.0
six==1.16.0
typing==3.7.4
typing_extensions==4.0.1
urllib3==1.25.3
virtualenv==20.10.0
wcwidth==0.2.5

And the command line

pip install -r bpython310.1.txt -v -v -v --log ./cwcwidth_0.1.5.log

I was able to reproduce a virtualenv environment in which bpython would once again get a Memory Error on start up.  The log file cwcwidth_0.1.5.log is attached in case you are still curious to see what was going wrong.  

But it works with cwcwidth 0.1.6, so if would be just if you are curious
[cwcwidth_0.1.5.log](https://github.com/bpython/bpython/files/7788580/cwcwidth_0.1.5.log)
.
