### ISSUE TITLE
Build bpython 0.12 Failed with Sphinx 1.1.2

### ISSUE THREAD

**Issue by ikanobori** [bpython/bpython#241]
Hi, 

I failed to install bpython with the following error:

```
Downloading/unpacking bpython
  Downloading bpython-0.12.tar.gz (130Kb): 130Kb downloaded
  Running setup.py egg_info for package bpython

    warning: no files found matching 'bpython/translations/*/LC_MESSAGES/bpython.mo'
Requirement already satisfied (use --upgrade to upgrade): pygments in /Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages (from bpython)
Installing collected packages: bpython
  Running setup.py install for bpython
    Running Sphinx v1.1.2
    loading pickled environment... not yet created
    building [man]: all manpages
    updating environment: 15 added, 0 changed, 0 removed
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/sho/.virtualenvs/test-bpython/build/bpython/setup.py", line 162, in <module>
        test_suite = 'bpython.test'
      File "/usr/local/Cellar/python/2.7.1/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.1/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.1/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/usr/local/Cellar/python/2.7.1/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/2.7.1/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.1/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/2.7.1/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/2.7.1/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.1/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/setup_command.py", line 140, in run
        app.build(force_all=self.all_files)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/application.py", line 204, in build
        self.builder.build_update()
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 191, in build_update
        self.build(['__all__'], to_build)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 216, in build
        purple, length):
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 120, in status_iterator
        for item in iterable:
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/environment.py", line 613, in update_generator
        self.read_doc(docname, app=app)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/environment.py", line 761, in read_doc
        pub.publish()
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
        self.settings)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/readers/__init__.py", line 72, in read
        self.parse()
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
        self.parser.parse(self.input, document)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
        self.statemachine.run(inputlines, document, inliner=self.inliner)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 174, in run
        input_source=document['source'])
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2706, in underline
        self.section(title, source, style, lineno - 1, messages)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 331, in section
        self.new_subsection(title, lineno, messages)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 399, in new_subsection
        node=section_node, match_titles=True)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 286, in nested_parse
        node=node, match_titles=match_titles)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 199, in run
        results = StateMachineWS.run(self, input_lines, input_offset)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2720, in text
        paragraph, literalnext = self.paragraph(lines, startline)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 422, in paragraph
        textnodes, messages = self.inline_text(text, lineno)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 431, in inline_text
        return self.inliner.parse(text, lineno, self.memo, self.parent)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 517, in parse
        lineno)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 779, in interpreted_or_phrase_ref
        lineno)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 836, in interpreted
        nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/domains/__init__.py", line 173, in role_adapter
        inliner, options, content)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/roles.py", line 130, in __call__
        set_role_source_info(inliner, lineno, refnode)
      File "/Users/sho/.virtualenvs/test-bpython/lib/python2.7/site-packages/sphinx/util/nodes.py", line 183, in set_role_source_info
        inliner.reporter.locator(lineno)
    AttributeError: Reporter instance has no attribute 'locator'
```

I installed bpython successfully after I upgraded Sphinx from 1.1.2 to 1.1.3.
## Environment
- Python: 2.7.1
- Sphinx: 1.1.2
- bpython: 0.12
### pip freeze

```
Jinja2==2.6
Pygments==1.6
Sphinx==1.1.2
distribute==0.6.24
docutils==0.10
wsgiref==0.1.2
```

---
- Bitbucket: https://bitbucket.org/bobf/bpython/issue/241
- Originally Reported By: [Sho Shimauchi](http://bitbucket.org/shiumachi)
- Originally Created At: 2013-03-29T08:56:07.609
